[2024-11-08T18:03:53.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T18:03:53.155+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: neon_backup_v2.perform_neon_backup scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2024-11-08T18:03:53.274+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: neon_backup_v2.perform_neon_backup scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2024-11-08T18:03:53.276+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-08T18:03:53.395+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): perform_neon_backup> on 2024-10-01 00:00:00+00:00
[2024-11-08T18:03:53.536+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=541) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-08T18:03:53.539+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'neon_backup_v2', 'perform_neon_backup', 'scheduled__2024-10-01T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/backup_dag.py', '--cfg-path', '/tmp/tmppzl4q5vl']
[2024-11-08T18:03:53.548+0000] {standard_task_runner.py:105} INFO - Job 162: Subtask perform_neon_backup
[2024-11-08T18:03:53.552+0000] {standard_task_runner.py:72} INFO - Started process 543 to run task
[2024-11-08T18:03:54.002+0000] {task_command.py:467} INFO - Running <TaskInstance: neon_backup_v2.perform_neon_backup scheduled__2024-10-01T00:00:00+00:00 [running]> on host 641085defe8e
[2024-11-08T18:03:54.496+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='neon_backup_v2' AIRFLOW_CTX_TASK_ID='perform_neon_backup' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T00:00:00+00:00'
[2024-11-08T18:03:54.498+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T18:03:54.577+0000] {backup_dag.py:12} INFO - Démarrage du backup Neon...
[2024-11-08T18:04:01.475+0000] {backup_dag.py:31} INFO - Nombre de lignes dans fraud_transactions: 0
[2024-11-08T18:04:01.578+0000] {backup_dag.py:31} INFO - Nombre de lignes dans normal_transactions: 0
[2024-11-08T18:04:01.687+0000] {backup_dag.py:56} INFO - Table fraud_transactions est vide, pas de backup nécessaire
[2024-11-08T18:04:01.689+0000] {backup_dag.py:56} INFO - Table normal_transactions est vide, pas de backup nécessaire
[2024-11-08T18:04:01.689+0000] {backup_dag.py:59} WARNING - Aucun fichier de backup créé - toutes les tables sont vides
[2024-11-08T18:04:01.689+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-08T18:04:01.727+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T18:04:01.727+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=neon_backup_v2, task_id=perform_neon_backup, run_id=scheduled__2024-10-01T00:00:00+00:00, execution_date=20241001T000000, start_date=20241108T180353, end_date=20241108T180401
[2024-11-08T18:04:01.786+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-08T18:04:01.824+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T18:04:01.828+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-24T15:33:01.123+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T15:33:01.222+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: neon_backup_v2.perform_neon_backup scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2024-11-24T15:33:01.257+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: neon_backup_v2.perform_neon_backup scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2024-11-24T15:33:01.258+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-24T15:33:01.296+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): perform_neon_backup> on 2024-10-01 00:00:00+00:00
[2024-11-24T15:33:01.323+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1335) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-24T15:33:01.326+0000] {standard_task_runner.py:72} INFO - Started process 1341 to run task
[2024-11-24T15:33:01.345+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'neon_backup_v2', 'perform_neon_backup', 'scheduled__2024-10-01T00:00:00+00:00', '--job-id', '627', '--raw', '--subdir', 'DAGS_FOLDER/backup_dag.py', '--cfg-path', '/tmp/tmpwfrzi6zv']
[2024-11-24T15:33:01.357+0000] {standard_task_runner.py:105} INFO - Job 627: Subtask perform_neon_backup
[2024-11-24T15:33:01.727+0000] {task_command.py:467} INFO - Running <TaskInstance: neon_backup_v2.perform_neon_backup scheduled__2024-10-01T00:00:00+00:00 [running]> on host 345e92ff26bf
[2024-11-24T15:33:02.044+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='neon_backup_v2' AIRFLOW_CTX_TASK_ID='perform_neon_backup' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T00:00:00+00:00'
[2024-11-24T15:33:02.046+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T15:33:02.069+0000] {backup_dag.py:12} INFO - Démarrage du backup Neon...
[2024-11-24T15:33:10.282+0000] {backup_dag.py:31} INFO - Nombre de lignes dans fraud_transactions: 5
[2024-11-24T15:33:10.879+0000] {backup_dag.py:31} INFO - Nombre de lignes dans normal_transactions: 155
[2024-11-24T15:33:11.488+0000] {backup_dag.py:40} INFO - Sauvegarde de fraud_transactions (5 lignes)...
[2024-11-24T15:33:14.167+0000] {backup_dag.py:52} INFO - Fichier créé: /opt/***/backups/fraud_transactions_202411.csv (0.00 MB)
[2024-11-24T15:33:14.170+0000] {backup_dag.py:40} INFO - Sauvegarde de normal_transactions (155 lignes)...
[2024-11-24T15:33:16.711+0000] {backup_dag.py:52} INFO - Fichier créé: /opt/***/backups/normal_transactions_202411.csv (0.04 MB)
[2024-11-24T15:33:16.975+0000] {backup_dag.py:71} INFO - Upload vers S3: backups/202411/fraud_transactions_202411.csv
[2024-11-24T15:33:23.192+0000] {backup_dag.py:77} INFO - Upload vérifié pour backups/202411/fraud_transactions_202411.csv
[2024-11-24T15:33:23.195+0000] {backup_dag.py:71} INFO - Upload vers S3: backups/202411/normal_transactions_202411.csv
[2024-11-24T15:33:25.013+0000] {backup_dag.py:77} INFO - Upload vérifié pour backups/202411/normal_transactions_202411.csv
[2024-11-24T15:33:32.274+0000] {backup_dag.py:111} INFO - Backup Neon terminé avec succès
[2024-11-24T15:33:32.296+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-24T15:33:32.327+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T15:33:32.329+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=neon_backup_v2, task_id=perform_neon_backup, run_id=scheduled__2024-10-01T00:00:00+00:00, execution_date=20241001T000000, start_date=20241124T153301, end_date=20241124T153332
[2024-11-24T15:33:32.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-24T15:33:32.445+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T15:33:32.456+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
