[2024-11-23T17:49:00.197+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T17:49:00.294+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection.process_transaction scheduled__2024-11-23T17:47:00+00:00 [queued]>
[2024-11-23T17:49:00.317+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection.process_transaction scheduled__2024-11-23T17:47:00+00:00 [queued]>
[2024-11-23T17:49:00.322+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-23T17:49:00.378+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): process_transaction> on 2024-11-23 17:47:00+00:00
[2024-11-23T17:49:00.410+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3134) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T17:49:00.422+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection', 'process_transaction', 'scheduled__2024-11-23T17:47:00+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_dag.py', '--cfg-path', '/tmp/tmpinqkbxi9']
[2024-11-23T17:49:00.427+0000] {standard_task_runner.py:105} INFO - Job 297: Subtask process_transaction
[2024-11-23T17:49:00.438+0000] {standard_task_runner.py:72} INFO - Started process 3139 to run task
[2024-11-23T17:49:01.114+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection.process_transaction scheduled__2024-11-23T17:47:00+00:00 [running]> on host 345e92ff26bf
[2024-11-23T17:49:02.385+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='fraud_detection' AIRFLOW_CTX_TASK_ID='process_transaction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T17:47:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T17:47:00+00:00'
[2024-11-23T17:49:02.411+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T17:49:02.442+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-11-23T17:49:02.566+0000] {fraud_detection_dag.py:78} INFO - Données récupérées depuis XCom: {"columns":["cc_num","merchant","category","amt","first","last","gender","street","city","state","zip","lat","long","city_pop","job","dob","trans_num","merch_lat","merch_long","is_fraud","current_time"],"index":[153811],"data":[[4018105808392773675,"fraud_Schamberger-O'Keefe","grocery_pos",121.68,"Katherine","Love","F","5884 Sandoval Square Apt. 371","Allenhurst","NJ",7711,40.2367,-74.0067,1533,"Administrator, charities\/voluntary organisations","1935-04-15","3184c7dc0e20a385e1ff3fd865fc9183",40.226006,-74.011296,0,1732384133863]]}
[2024-11-23T17:49:02.572+0000] {fraud_detection_dag.py:86} INFO - Données JSON parsées avec succès
[2024-11-23T17:49:02.701+0000] {fraud_detection_dag.py:90} INFO - DataFrame créé avec 1 lignes
[2024-11-23T17:49:03.003+0000] {fraud_detection_dag.py:94} INFO - Colonnes renommées avec succès
[2024-11-23T17:49:03.004+0000] {fraud_detection_dag.py:95} INFO - Colonnes disponibles: ['cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'merch_lat', 'merch_long', 'is_fraud', 'trans_date_trans_time']
[2024-11-23T17:49:03.008+0000] {fraud_detection_dag.py:99} INFO - Conversion de trans_date_trans_time en unix_time réussie
[2024-11-23T17:49:03.094+0000] {fraud_detection_dag.py:108} INFO - Transformation des données...
[2024-11-23T17:49:08.021+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:172: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = min(effective_n_jobs(n_jobs), n_estimators)

[2024-11-23T17:49:08.041+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:172: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = min(effective_n_jobs(n_jobs), n_estimators)

[2024-11-23T17:49:08.047+0000] {fraud_detection_dag.py:120} INFO - Prediction de fraude: NORMAL, Probabilité: 40.32%
[2024-11-23T17:49:08.869+0000] {fraud_detection_dag.py:126} INFO - Prédiction: NORMAL (Probabilité: 40.32%)
[2024-11-23T17:49:08.917+0000] {python.py:240} INFO - Done. Returned value was: notify_normal
[2024-11-23T17:49:09.045+0000] {branch.py:38} INFO - Branch into notify_normal
[2024-11-23T17:49:09.047+0000] {skipmixin.py:230} INFO - Following branch ('notify_normal',)
[2024-11-23T17:49:09.138+0000] {skipmixin.py:278} INFO - Skipping tasks [('notify_fraud', -1), ('skip_processing', -1)]
[2024-11-23T17:49:09.384+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T17:49:09.385+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fraud_detection, task_id=process_transaction, run_id=scheduled__2024-11-23T17:47:00+00:00, execution_date=20241123T174700, start_date=20241123T174900, end_date=20241123T174909
[2024-11-23T17:49:09.751+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T17:49:10.276+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-23T17:49:10.358+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-23T17:49:10.514+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
