[2024-11-23T18:07:40.572+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T18:07:40.651+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection.log_to_mlflow scheduled__2024-11-23T18:05:00+00:00 [queued]>
[2024-11-23T18:07:40.699+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection.log_to_mlflow scheduled__2024-11-23T18:05:00+00:00 [queued]>
[2024-11-23T18:07:40.701+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-23T18:07:40.784+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): log_to_mlflow> on 2024-11-23 18:05:00+00:00
[2024-11-23T18:07:40.816+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4451) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T18:07:40.820+0000] {standard_task_runner.py:72} INFO - Started process 4456 to run task
[2024-11-23T18:07:40.833+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection', 'log_to_mlflow', 'scheduled__2024-11-23T18:05:00+00:00', '--job-id', '444', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_dag.py', '--cfg-path', '/tmp/tmp6n2zjnba']
[2024-11-23T18:07:40.844+0000] {standard_task_runner.py:105} INFO - Job 444: Subtask log_to_mlflow
[2024-11-23T18:07:41.075+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection.log_to_mlflow scheduled__2024-11-23T18:05:00+00:00 [running]> on host 345e92ff26bf
[2024-11-23T18:07:41.487+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='fraud_detection' AIRFLOW_CTX_TASK_ID='log_to_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T18:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T18:05:00+00:00'
[2024-11-23T18:07:41.491+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T18:07:49.284+0000] {fraud_detection_dag.py:354} INFO - Vérification des artefacts existants dans le bucket fraud-detection-bucket-jedha au préfixe mlartifacts/model/...
[2024-11-23T18:07:51.391+0000] {fraud_detection_dag.py:367} INFO - Aucun artefact à supprimer.
[2024-11-23T18:07:51.602+0000] {logging_mixin.py:190} WARNING - 2024/11/23 18:07:51 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-11-23T18:08:08.364+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-11-23T18:08:32.929+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T18:08:33.236+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T18:08:33.238+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fraud_detection, task_id=log_to_mlflow, run_id=scheduled__2024-11-23T18:05:00+00:00, execution_date=20241123T180500, start_date=20241123T180740, end_date=20241123T180833
[2024-11-23T18:08:33.977+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T18:08:34.131+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T18:08:34.157+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
